name: login

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Step 1 - Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 - Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

      - name: Step 3 - Run Postman Collection and generate report
        run: |
          mkdir -p ./result
          newman run ./2_login.json -g ./global.json -e ./Hom.json \
            --delay-request 1 \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export ./result/index.html \
            --reporter-htmlextra-skipAssets

      - name: Debug - List arquivos gerados
        run: ls -R ./result

      - name: Step 4 - Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
